import React from 'react';
import { motion, Variants } from 'framer-motion';
import { DocumentReportIcon, DocumentDownloadIcon, ClockIcon, ShieldCheckIcon, TemplateIcon } from '../components/Icons';
import { recentReports, scheduledReports, auditLog } from '../constants';
import { RecentReport, ScheduledReport, AuditLogEntry } from '../types';


const itemVariants: Variants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      duration: 0.5,
      ease: 'easeOut',
    },
  },
};

const AnimatedSection: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className }) => (
    <motion.div
        className={className}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.2 }}
        variants={itemVariants}
    >
        {children}
    </motion.div>
);

const ReportGenerator: React.FC = () => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">Generate New Report</h3>
        <form className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Report Type</label>
                <select className="mt-1 block w-full p-2 bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md">
                    <option>Sales Summary</option>
                    <option>User Engagement</option>
                    <option>Financial Overview</option>
                </select>
            </div>
            <div>
                <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Date Range</label>
                <input type="date" className="mt-1 block w-full p-2 bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md" />
            </div>
            <div className="md:col-span-2">
                <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Recipients (comma-separated)</label>
                <input type="text" placeholder="alex@example.com, casey@example.com" className="mt-1 block w-full p-2 bg-gray-50 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md" />
            </div>
            <div className="md:col-span-2 text-right">
                <button type="submit" className="bg-accent-blue text-white px-6 py-2 rounded-lg font-semibold hover:bg-blue-600">
                    Generate
                </button>
            </div>
        </form>
    </div>
);

const RecentReports: React.FC<{ reports: RecentReport[] }> = ({ reports }) => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">Recent Reports</h3>
        <ul className="space-y-3">
            {reports.map(report => (
                <li key={report.id} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg">
                    <div className="flex items-center">
                        <DocumentReportIcon className="w-6 h-6 text-accent-blue mr-4" />
                        <div>
                            <p className="font-semibold">{report.title}</p>
                            <p className="text-xs text-gray-500">Generated by {report.author} on {report.generated}</p>
                        </div>
                    </div>
                    <button>
                        <DocumentDownloadIcon className="w-5 h-5 text-gray-500 hover:text-accent-blue" />
                    </button>
                </li>
            ))}
        </ul>
    </div>
);

const ScheduledReports: React.FC<{ reports: ScheduledReport[] }> = ({ reports }) => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">Scheduled Reports</h3>
         <ul className="space-y-3">
            {reports.map(report => (
                <li key={report.id} className="flex items-center justify-between">
                    <div>
                        <p className="font-semibold">{report.title}</p>
                        <p className="text-xs text-gray-500">Frequency: {report.frequency} | Next run: {report.nextRun}</p>
                    </div>
                    <ClockIcon className="w-5 h-5 text-gray-400" />
                </li>
            ))}
        </ul>
    </div>
);

const ReportTemplates: React.FC = () => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">Templates</h3>
        <div className="grid grid-cols-2 gap-4">
            {['Marketing', 'Sales', 'Finance', 'Engineering'].map(name => (
                 <button key={name} className="flex items-center p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                    <TemplateIcon className="w-5 h-5 text-accent-blue mr-3" />
                    <span className="font-medium">{name} Template</span>
                </button>
            ))}
        </div>
    </div>
);

const ExportCenter: React.FC = () => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">Export Center</h3>
        <p className="text-sm text-gray-500 mb-4">Download your complete data archives.</p>
        <div className="flex space-x-4">
            <button className="flex-1 bg-green-500 text-white py-2 rounded-lg font-semibold hover:bg-green-600">Export as XLS</button>
            <button className="flex-1 bg-red-500 text-white py-2 rounded-lg font-semibold hover:bg-red-600">Export as PDF</button>
            <button className="flex-1 bg-gray-600 text-white py-2 rounded-lg font-semibold hover:bg-gray-700">Export as CSV</button>
        </div>
    </div>
);

const AuditLog: React.FC<{ log: AuditLogEntry[] }> = ({ log }) => (
    <div className="bg-light-card dark:bg-dark-card p-6 rounded-xl shadow-sm">
        <div className="flex items-center mb-4">
            <ShieldCheckIcon className="w-6 h-6 mr-3 text-accent-blue" />
            <h3 className="text-lg font-semibold text-gray-800 dark:text-white">Audit Log</h3>
        </div>
        <ul className="space-y-3 text-sm h-64 overflow-y-auto">
             {log.map(entry => (
                <li key={entry.id} className="flex items-start">
                    <img src={entry.user.avatar} alt={entry.user.name} className="w-8 h-8 rounded-full mr-3 mt-1" />
                    <div>
                        <p><span className="font-semibold">{entry.user.name}</span> {entry.action}</p>
                        <p className="text-xs text-gray-500">{entry.timestamp} from IP: {entry.ip}</p>
                    </div>
                </li>
            ))}
        </ul>
    </div>
);


const ReportsPage: React.FC = () => {
  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={{ visible: { transition: { staggerChildren: 0.1 } } }}
      className="space-y-6"
    >
      <AnimatedSection>
        <ReportGenerator />
      </AnimatedSection>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <AnimatedSection>
            <RecentReports reports={recentReports} />
        </AnimatedSection>
        <AnimatedSection>
            <ScheduledReports reports={scheduledReports} />
        </AnimatedSection>
      </div>

       <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <AnimatedSection><ReportTemplates /></AnimatedSection>
            <AnimatedSection><ExportCenter /></AnimatedSection>
       </div>
       
      <AnimatedSection>
        <AuditLog log={auditLog} />
      </AnimatedSection>
    </motion.div>
  );
};

export default ReportsPage;